// src/react/BridgePortalElementChild.jsx
import {
  useContext,
  useEffect,
  useRef,
} from 'react'

import BridgePortalElementContext from '../react/BridgePortalElementContext'

const BridgePortalElementChild = () => {
  const {
    getChildElement,
  } = (
    useContext(
      BridgePortalElementContext
    )
  )

  const domElementRef = useRef()
  
  useEffect(
    () => {
      getChildElement(
        domElementRef
        .current
      )
    },
    [],
  )
  
  return (
    <div ref={domElementRef} />
  )
}

export default BridgePortalElementChild

// src/solid/BridgePortalElementChild.jsx
import {
  useContext,
} from 'solid-js'

import BridgePortalElementContext from '../solid/BridgePortalElementContext'

const BridgePortalElementChild = () => {
  const {
    getChildElement,
  } = (
    useContext(
      BridgePortalElementContext
    )
  )
  
  const domElement = <div />

  getChildElement(
    domElement
  )
  
  return domElement
}

export default BridgePortalElementChild
